### ISSUE TITLE
codes

### ISSUE THREAD

**Issue by Jane03** [cui-unige/rewriting-Jane03#1]
Bonjour monsieur,

j'ai cette erreur et je n'arrive pas trop à savoir pourquoi.
"Error -> src/adt/init_spec.lua @ 368
#test adt can create and apply a bottomup strategy
./src/adt/init.lua:64: attempt to index a nil value (local 'key')

stack traceback:
	./src/adt/init.lua:64: in metamethod '__index'
	./src/adt/boolean.lua:29: in main chunk
"

Pouvez vous m'aider? Merci

**Comment by Jane03** [comment]
J'ai rechangé mes codes mais le problème persiste.

**Comment by Jane03** [comment]
Bonjour monsieur,
Maintenant j'ai aussi cela comme erreur:
Error -> src/adt/init_spec.lua @ 352
#test adt can create and apply a try strategy
./src/adt/init.lua:351: attempt to call a nil value (field '?')

stack traceback:
	./src/adt/init.lua:351: in local 'fun'
	/usr/local/share/lua/5.3/fun.lua:30: in upvalue 'call_if_not_empty'
	/usr/local/share/lua/5.3/fun.lua:180: in function </usr/local/share/lua/5.3/fun.lua:178>
	(...tail calls...)
	src/adt/init_spec.lua:362: in function <src/adt/init_spec.lua:352>

**Comment by saucisson** [comment]
Je pourrais mieux voir le problème si tu faisais un commit/push de ton code !

**Comment by Jane03** [comment]
voilà c'est fait

**Comment by saucisson** [comment]
Première chose : dans les ADT, les axiomes ont été remplacés par des règles de réécriture.
Par exemple `Adt.axioms` devient `Adt.rules` et `Adt.axiom` devient `Adt.rule`.

**Comment by saucisson** [comment]
L'erreur `./src/adt/boolean.lua:78: attempt to call field '_b' (a table value)` est causée par `Boolean._b {}`. C'est une variable et non un terme, donc il faut supprimer les `{}` (qui permettent de créer un terme à partir d'une opération).

**Comment by saucisson** [comment]
Concernant l'erreur `./src/adt/init.lua:352: attempt to call a nil value`, je ne comprend pas ce que tu veux faire avec la ligne 352: `if t[k](term) ~= nil then`. Ici, `k` est l'une des stratégies passées en paramètre à `choice`. Ce que tu veux tester, c'est que cette stratégie s'applique au terme `term`.

**Comment by saucisson** [comment]
`src/adt/init_spec.lua:343: attempt to call field 'binary' (a nil value)`: il n'y a pas d'opérateur `binary` dans le sort utilisé en exemple, uniquement `empty` et `cons`.

**Comment by Jane03** [comment]
ok mais pourtant j'avais mis adt.rules

**Comment by Jane03** [comment]
ok je vais revoir mes codes

**Comment by saucisson** [comment]
Voilà j'ai fini les commentaires pour l'instant :-)

**Comment by Jane03** [comment]
Merci bcp et le deadline c'est demain
